In [1]:
import pandas as pd
import numpy as np

In [18]:
min_max = ([0, 999999], [0, 99999.99999])


def make_series(low, high, name):
    if any(isinstance(_, float) for _ in (low, high)):
        func = np.random.uniform
    else:
        func = np.random.randint
    return pd.Series(func(low, high, size=(50,)), name=name)


pd.concat([make_series(lo, hi, name) for (lo, hi), name in zip(min_max, "AB")],
          axis=1)

         A             B
0   373468  20096.068606
1   610228  94294.561178
2   221136  89561.879606
3   556010  60357.735550
4   902891  42560.683514
5   151540  58940.940633
6   791601  23821.166496
7   855345  19231.300401
8    47828  40479.889398
9   110479  27088.207124
10   47379  82385.664040
11  588044  39853.393832
12  601858  32226.147607
13  292908   8170.057733
14  391341  83836.624474
15  445463  94842.459479
16  200113  57665.094649
17   18891  33347.795851
18  348047  79661.958500
19   95281  26959.067517
20   44771  50451.783134
21  845063  25397.061517
22   85237  59595.416350
23  574172  50720.020047
24  785986  99797.993255
25  127068  18000.234719
26  901834  85426.096632
27  421117  69448.951749
28  692812   3990.505625
29  106087  60747.615480
30  365039  83430.026536
31  720321   4805.707799
32  645677  57321.981581
33  469682  54796.024776
34  898488  96762.182014
35  641959  95175.168883
36  655475  94675.591106
37  389865  36351.794688
38  788905  22904.689825
39  824500  50291.894393
40  448840    786.228050
41  403822  85718.141859
42  376456  97564.831122
43  148047  17626.010196
44  518119  19665.873772
45  977944  92025.589551
46  616071   5059.005221
47  722360  96538.192436
48  536419  67291.645746
49  995065  91665.991958